#!/bin/sh
#
# fixup        Prepares network and sshd.
#

umask 077

start() {
	ip link set dev eth0 address 00:18:3E:02:E3:7F
	ip link set dev lo up
	chown root:root /etc/ssh/ssh_host_*
	chmod 600 /etc/ssh/ssh_host_*key
}
stop() {
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

