#!/bin/sh
#
# scratchfs           Create a /scratch and mount there a permanent file system
#

start() {
    mkdir -p /scratch
    mount /dev/mmcblk0p3 /scratch
    echo "/scratch successfully mounted" > /dev/console
}

stop() {
    echo "Unmounting /scratch..."
    umount /scratch
    echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
