#!/bin/sh

start() {
cat > /dev/console << 'EOF'
                _                  
     /\        (_)                 
    /  \   _ __ _  __ _ _ __   ___ 
   / /\ \ | '__| |/ _` | '_ \ / _ \
  / ____ \| |  | | (_| | | | |  __/
 /_/    \_\_|  |_|\__,_|_| |_|\___|
                                    
~ Simple Linux on RISC-V Softcores ~

EOF
}

stop() {
    :
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
